### ISSUE TITLE
新建完配置后怎么把这个配置当做当前配置的？

### ISSUE THREAD

**Issue by desertsss** [Stapxs/N2N-Desktop#1]
请问下：

我新建了一个配置，但是主页里面，配置信息还是空，这是为什么的？如何应用到首页去？

谢谢

**Comment by Stapxs** [comment]
呜呜居然有人用诶
这还是个半成品，功能可能不怎么全
在配置名前点击就好啦，或者在托盘图标右击选择
![图片](https://stapx.chuhelan.com/lib/pic/n.png)

**Comment by Stapxs** [comment]
# 更新了下 README 交代一下 QAQ
更新了下 README 交代一下 ，防止之后有人找到不会用什么的（跑

~~~
半成品警告：这玩意还没做完，有一吨的 BUG 和 基础功能未完成！
~~~

# N2N-Desktop
这是个 GUI 的 N2N 启动与管理程序 / This is a GUI N2N startup and management program

# 这是啥
N2N 是个超级棒的轻型 VPN 软件，既然你都找到这个项目了，那我就不过多介绍了，本程序是因为我想用 N2N 但又苦恼没有一个好看又方便的 GUI 莱管理 N2N 的运行，就写了……

# 怎么用
这儿说一些比较特殊的设计：

- 点击配置名前启用配置


![图片](https://stapx.chuhelan.com/lib/pic/n.png)


- 右击运行按钮可以显示 N2N 的运行 log，同时也会输出进程守护的相关日志！

# 提醒
- 这玩意只是个半成品 —— （超大声，有不少已知或者未知的 BUG，突然炸了我也没输出日志啥的 = =，当时做了只是自己用的没考虑那么多。
- 关闭前务必点击停止，本程序不会在退出时自动结束 edge.exe 的进程，所以，如果由于 BUG 闪退也请去任务管理器里结束掉 N2N 的 edge.exe 的进程。

# 更新
如果有空，我会继续做完它的，相信我 ——

**Comment by desertsss** [comment]
哈哈，这个确实用的人少，不过还是有用的。昨天还有个issue，我另开一个session吧
